### ISSUE TITLE
Not working: NOTHING CONSUMED error

### ISSUE THREAD

**Issue by mhabets** [AbeEstrada/atom-format-sql#15]
With Atom 1.7.0 on linux, I get the following error message in the console:

```
Error: NOTHING CONSUMED: Stopped at - ';
'
   at new Lexer (/home/user/.atom/packages/format-sql/node_modules/sql-parser/lib/lexer.js:18:17)
    at Object.exports.tokenize (/home/user/.atom/packages/format-sql/node_modules/sql-parser/lib/lexer.js:176:13)
    at formatSql (/home/user/.atom/packages/format-sql/lib/format-sql.coffee:26:26)
    at atom-workspace.atom.commands.add.format:sql (/home/user/.atom/packages/format-sql/lib/format-sql.coffee:7:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by Allendar** [comment]
Yep got this too:

```
Error: NOTHING CONSUMED: Stopped at - ' eol.`id`,(…) // format-sql.coffee:42
Error: NOTHING CONSUMED: Stopped at - ' eol.`id`,(…) // format-sql.coffee:29
```

**Comment by gegewuwr** [comment]
Same here:

```
Error: NOTHING CONSUMED: Stopped at - ';'
    at new Lexer (/Users/wangran/.atom/packages/format-sql/node_modules/sql-parser/lib/lexer.js:18:17)
    at Object.exports.tokenize (/Users/wangran/.atom/packages/format-sql/node_modules/sql-parser/lib/lexer.js:176:13)
    at formatSql (/Users/wangran/.atom/packages/format-sql/lib/format-sql.coffee:26:26)
    at atom-workspace.atom.commands.add.format:sql (/Users/wangran/.atom/packages/format-sql/lib/format-sql.coffee:7:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by amehb** [comment]
"Me too".
